"""phase1_domain_changes

Revision ID: 7a9769efe58d
Revises: 5cf5cc9739d7
Create Date: 2026-07-12 14:36:35.942065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a9769efe58d'
down_revision: Union[str, Sequence[str], None] = '5cf5cc9739d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_anomalies', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_import_anomalies_decision_id_decisions'), 'decisions', ['decision_id'], ['id'])

    with op.batch_alter_table('import_reports', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_import_reports_import_id'), ['import_id'])

    with op.batch_alter_table('imports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pipeline_stage', sa.Enum('UPLOADING', 'PARSING', 'NORMALIZATION', 'VALIDATION', 'SIMILARITY', 'MEMBERSHIP', 'CURRENCY', 'SETTLEMENT', 'PREVIEW', 'COMMIT', 'FINISHED', name='importpipelinestage'), nullable=True))
        batch_op.add_column(sa.Column('processing_duration_ms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_rows', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('successful_rows', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('failed_rows', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pending_review_rows', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('health_score', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('import_version', sa.Integer(), nullable=True))

    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_ledger_entries_settlement_id_settlements'), 'settlements', ['settlement_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ledger_entries_settlement_id_settlements'), type_='foreignkey')

    with op.batch_alter_table('imports', schema=None) as batch_op:
        batch_op.drop_column('import_version')
        batch_op.drop_column('health_score')
        batch_op.drop_column('pending_review_rows')
        batch_op.drop_column('failed_rows')
        batch_op.drop_column('successful_rows')
        batch_op.drop_column('total_rows')
        batch_op.drop_column('processing_duration_ms')
        batch_op.drop_column('pipeline_stage')

    with op.batch_alter_table('import_reports', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_import_reports_import_id'), type_='unique')

    with op.batch_alter_table('import_anomalies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_import_anomalies_decision_id_decisions'), type_='foreignkey')

    # ### end Alembic commands ###
