"""phase3_explainability_metrics

Revision ID: a39ca27998bd
Revises: 7a9769efe58d
Create Date: 2026-07-12 14:50:18.026080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39ca27998bd'
down_revision: Union[str, Sequence[str], None] = '7a9769efe58d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_anomalies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_row', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('normalized_row', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('explainability_metrics', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_anomalies', schema=None) as batch_op:
        batch_op.drop_column('explainability_metrics')
        batch_op.drop_column('normalized_row')
        batch_op.drop_column('original_row')

    # ### end Alembic commands ###
